version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - nuget: "github-actions"
    directory: "/code/"
    schedule:
      interval: "weekly"
